### ISSUE TITLE
Update peer dependencies for prop-types 15.6.1

### ISSUE THREAD

**Issue by ikappas** [lifeiscontent/react-svg-injector#3]
When the package is installed with prop-types 15.6.1 it displays the following warning:

```bash
react-svg-injector@1.0.2" has incorrect peer dependency "prop-types@15.6.0".
```

**Comment by lifeiscontent** [comment]
@ikappas do you think you could try and make this failing test pass? I've updated the dependencies but couldn't get the test to pass.

https://github.com/lifeiscontent/react-svg-injector/pull/2

if you do that, I'll update the package. Unfortunately I don't have spare time right now to do it.

**Comment by lifeiscontent** [comment]
@ikappas hey, I took your PR and merged it in after I made a few fixes. Thanks for the help 👍

**Comment by lifeiscontent** [comment]
let me know if you have any issues with the new release.

**Comment by lifeiscontent** [comment]
@ikappas for some reason I can't get the build to publish a new release, do you have much experience with semantic-release?

**Comment by lifeiscontent** [comment]
in effort to make things easier for you, I've added you as a collaborator. https://github.com/lifeiscontent/react-svg-injector/invitations

**Comment by ikappas** [comment]
@lifeiscontent I don't have experience with semantic-release but I could have a look

**Comment by lifeiscontent** [comment]
@ikappas cool, let me know if I can help you with anything. I'm sorry for the breaking change. 😞

**Comment by lifeiscontent** [comment]
@ikappas what are your general use cases for this library? I'm gonna clean it up and rewrite it for react 16.3. can you show me some examples of what you'd expect from this library so I can optimize for those cases?

**Comment by lifeiscontent** [comment]
@ikappas I've successfully deployed an update check out version 2.0.0

**Comment by lifeiscontent** [comment]
@ikappas please ping me if you have any issues.
